modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/matthewperiut/Chisel-Reborn/issues"
license = "GPLv2"

[[mods]]
modId = "chisel"
version = "${version}"
displayName = "Chisel Reborn"
authors = ["Slaincow", "KnowYourKnot", "Original Creator: AUTOMATIC_MAIDEN"]
description = '''
Adds New Blocks!
'''
logoFile = "assets/chisel/icon.png"

[[dependencies.chisel]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chisel]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chisel]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.91,)"
ordering = "AFTER"
side = "BOTH"